export default {
  'LOGOUT': 'LOGOUT',
  'BUILD_MENU': 'BUILD_MENU',
  'SAVE_USER_INFO': 'SAVE_USER_INFO',
  'ENTER_META_PAGE': 'ENTER_META_PAGE',
  'LEAVE_META_PAGE': 'LEAVE_META_PAGE',
  'MENU_ITEMS': {

  }
}
